// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fspollyConsole")>]
[<assembly: AssemblyProductAttribute("fspolly")>]
[<assembly: AssemblyDescriptionAttribute("F# retry functionality package inspired by the C# Polly library")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fspollyConsole"
    let [<Literal>] AssemblyProduct = "fspolly"
    let [<Literal>] AssemblyDescription = "F# retry functionality package inspired by the C# Polly library"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
